'use client'

import { useEffect, useState } from 'react'

// Braille-character world map — rasterized from Natural Earth 50m country vectors
// Each braille char encodes a 2×4 pixel grid → 156×104 effective pixel resolution
// col 0 ≈ 170°W, col 39 ≈ 0° (Greenwich), col 77 ≈ 166°E
// Generated by scripts/generate-braille-map.mjs
const MAP_WIDTH = 78
const MAP_ROWS = [
  '⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠀⣀⣤⣤⣦⣶⠶⣀⣠⣤⣤⣴⣶⣶⣶⣶⣦⡀⠤⠄⠀⠀⠀⠀⠀⠀⣀⣀⠀⠀⠀⠀⠀⠀⢠⠀⠀⠀⠀⠀⠀⠀⢀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀',
  '⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢤⠡⠤⠡⠡⠹⣘⠋⠏⠁⠙⠛⠻⢿⣿⣿⣿⣿⣿⣿⣿⡆⠀⠀⠀⠀⠀⠀⠈⠛⠁⠀⠀⠀⠀⠀⠀⠀⢀⠤⠄⠀⠀⠀⠀⣀⣀⣠⣼⣧⡤⠀⠀⠀⠀⠀⠠⠀⠀⠀⠀⠀⠀⠀⠀⠀',
  '⠀⢀⣠⣤⣤⣀⣀⣀⢀⣀⣛⡙⢓⣶⢦⢘⡺⡅⠧⡿⡻⣤⣄⠀⠀⠘⢿⣿⣿⣿⣿⣿⠛⠀⠀⠀⠀⠀⠀⠀⠀⡀⣀⣤⣤⣀⠀⠀⢀⠘⠃⢀⡀⣾⠠⣶⣽⣿⣿⣿⣿⣿⣿⣿⣷⣾⣧⣤⣤⣶⣴⣤⣤⣄⣀⡀⣀⣀',
  '⠀⢮⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣿⣿⣿⡿⠯⠅⠨⠸⡿⡗⠀⠀⢻⣿⡿⠛⠁⠀⠀⠤⠦⠀⠀⠀⠀⠀⣠⣾⠟⣻⣿⣏⣏⣾⣾⣿⣿⣿⣿⣿⣾⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣻',
  '⠀⠛⠿⣟⠛⠙⠛⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⢸⣷⣆⣤⠀⠀⠀⠙⠃⠀⠀⠀⠀⠀⠀⠀⢀⠄⠀⠿⢻⡿⠘⢿⣽⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠛⠛⠏⣩⡚⠛⠉⠀',
  '⠠⠀⠁⠀⠀⠀⠀⠀⠚⢿⣿⣿⣿⣿⣿⣿⣿⣿⣷⡆⢱⣿⣿⣿⣶⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⡎⣦⡀⣈⣭⣥⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣅⣠⠀⠀⢸⠟⠁⠀⠀⠀',
  '⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⢽⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡙⠡⠧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢭⣿⣿⣿⣿⣿⣿⣿⣿⢿⣿⣿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⢘⠀⠀⠈⠀⠀⠀⠀⠀',
  '⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠋⠊⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣤⣼⠟⠋⠳⡙⣿⣿⣃⣈⡙⣿⣇⠺⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠛⠁⠰⠀⠀⠀⠀⠀⠀⠀⠀',
  '⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⢟⣀⣠⡀⠄⠸⡘⠿⠿⣿⣿⣿⣀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡥⠙⡇⢀⣰⠇⠀⠀⠀⠀⠀⠀⠀⠀',
  '⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⡿⣿⣿⣿⣿⣿⠿⣿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣾⣿⣿⣿⣶⣄⣰⣤⣠⣰⣿⣿⡿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⠀⠀⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀',
  '⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠐⠹⣿⣿⠁⠀⠀⠘⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢩⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣎⣿⣿⣷⡜⡻⠿⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀',
  '⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⣿⡄⢠⠆⠈⠠⢄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢺⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠘⣿⣿⣿⡿⠀⠀⠘⣿⣿⡿⠋⢹⣿⣿⡟⡛⠉⠈⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀',
  '⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠋⠻⣴⡄⠀⠀⠀⠀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⣸⠿⠋⠀⠀⠀⠀⢹⣟⠁⠀⠀⠹⢿⣷⠀⠀⠸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀',
  '⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠆⢄⣾⣷⣴⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣶⠃⠀⠀⠀⠀⠈⢧⠀⠀⠀⠀⡀⠏⠀⠀⠀⢘⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀',
  '⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣶⡆⠀⠀⠀⠀⠀⠀⠀⠀⠈⠋⠉⠁⠛⣿⣿⣿⣿⣿⣿⣿⣿⠏⠀⠀⠀⠀⠀⠀⠈⠀⠀⠀⠢⣱⠀⢀⣴⠀⠈⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀',
  '⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠐⠀⠀⣿⣿⣿⣿⣿⣿⣷⣦⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢿⣿⣿⣿⣿⣿⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⡄⠻⢿⠨⠁⠂⢢⣠⣀⠀⠀⠀⠀⠀⠀⠀⠀',
  '⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢿⣿⣿⣿⣿⣿⣿⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⠠⠄⠀⢀⠀⠀⠸⢿⢷⠈⠀⢄⠀⠀⠀⠀',
  '⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣿⣿⣿⣿⣿⣿⣿⣿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⣿⣿⣿⣿⣿⠀⢀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡀⣴⠀⢠⠀⠀⠀⠀⠀⠀⠀⠀',
  '⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣿⣿⣿⣿⡿⠋⠰⡿⠀⢀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣷⣼⣇⠀⠀⠀⠀⠀⠀⠀',
  '⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣾⣿⣿⣿⣿⠟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⠗⠀⠸⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢾⣿⣿⣿⣿⣿⣿⣿⣦⠀⠀⠀⠀⠀⠀',
  '⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣿⣿⡿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀',
  '⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⣿⣿⠛⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠛⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⠋⠁⠀⠀⠻⣿⣿⡏⠀⠀⠀⠀⠠⠀',
  '⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⡟⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢤⠀⠀⠀⠀⠀⡄⠃',
  '⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢼⣿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠚⠀⠀',
  '⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⢏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀',
  '⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀',
]

interface Overlay {
  row: number
  col: number
  type: 'conflict' | 'population' | 'resource'
  label: string
}

// Overlay positions computed from lon/lat → braille char grid (verified against land)
const overlays: Overlay[] = [
  // Conflict zones (red, blinking)
  { row: 6, col: 44, type: 'conflict', label: 'Ukraine' },
  { row: 9, col: 46, type: 'conflict', label: 'Middle East' },
  { row: 12, col: 44, type: 'conflict', label: 'Sudan' },
  { row: 12, col: 38, type: 'conflict', label: 'Sahel' },
  { row: 11, col: 59, type: 'conflict', label: 'Myanmar' },

  // High population (bright green)
  { row: 11, col: 55, type: 'population', label: 'India' },
  { row: 8, col: 62, type: 'population', label: 'China' },
  { row: 12, col: 61, type: 'population', label: 'SE Asia' },
  { row: 13, col: 38, type: 'population', label: 'Nigeria' },
  { row: 10, col: 57, type: 'population', label: 'Bangladesh' },
  { row: 16, col: 63, type: 'population', label: 'Indonesia' },

  // Resource depletion (amber)
  { row: 15, col: 24, type: 'resource', label: 'Amazon' },
  { row: 1, col: 37, type: 'resource', label: 'Arctic Ice' },
  { row: 18, col: 71, type: 'resource', label: 'Great Barrier Reef' },
  { row: 3, col: 60, type: 'resource', label: 'Siberian Permafrost' },
  { row: 15, col: 43, type: 'resource', label: 'Congo Basin' },
]

export default function BrailleWorldMap() {
  const [activeCycle, setActiveCycle] = useState(0)

  useEffect(() => {
    const interval = setInterval(() => {
      setActiveCycle((c) => (c + 1) % 3)
    }, 1200)
    return () => clearInterval(interval)
  }, [])

  const overlayMap = new Map<string, Overlay>()
  overlays.forEach((o) => overlayMap.set(`${o.row},${o.col}`, o))

  return (
    <div className="border border-border bg-bg-panel p-4 md:p-6 crt-border">
      <div className="flex items-center gap-3 mb-4">
        <h3 className="font-heading text-base text-text-dim tracking-wider">
          SURFACE TELEMETRY — REAL-TIME MONITORING
        </h3>
        <span className="text-terminal text-xs radar-blink">● LIVE</span>
      </div>

      <div className="overflow-hidden flex justify-center">
        <pre
          className="font-mono select-none leading-[1.1]"
          style={{ fontSize: 'clamp(8px, 1.28vw, 14px)' }}
          aria-label="Braille world map showing conflict zones, population centers, and resource depletion areas"
        >
          {MAP_ROWS.map((row, rowIdx) => (
            <div key={rowIdx} className="whitespace-pre">
              {[...row].map((char, colIdx) => {
                const key = `${rowIdx},${colIdx}`
                const overlay = overlayMap.get(key)

                if (overlay) {
                  const isConflict = overlay.type === 'conflict'
                  const isPopulation = overlay.type === 'population'

                  if (isConflict) {
                    const visible = activeCycle !== (colIdx % 3)
                    return (
                      <span
                        key={colIdx}
                        className={`text-red text-glow-red ${visible ? 'opacity-100' : 'opacity-30'}`}
                        title={overlay.label}
                      >
                        ◆
                      </span>
                    )
                  }
                  if (isPopulation) {
                    return (
                      <span
                        key={colIdx}
                        className="text-terminal text-glow"
                        title={overlay.label}
                      >
                        ▲
                      </span>
                    )
                  }
                  // Resource depletion
                  return (
                    <span
                      key={colIdx}
                      className="text-amber text-glow-amber"
                      title={overlay.label}
                    >
                      ⚠
                    </span>
                  )
                }

                // Braille empty char (0x2800) = ocean, anything else = land
                if (char === '\u2800') {
                  return (
                    <span key={colIdx} className="text-text-dim/10">
                      {char}
                    </span>
                  )
                }

                return (
                  <span key={colIdx} className="text-terminal/40">
                    {char}
                  </span>
                )
              })}
            </div>
          ))}
        </pre>
      </div>

      {/* Legend */}
      <div className="flex flex-wrap gap-4 mt-4 text-xs font-mono">
        <span className="flex items-center gap-1.5">
          <span className="text-red text-glow-red">◆</span>
          <span className="text-text-dim">CONFLICT ZONE</span>
        </span>
        <span className="flex items-center gap-1.5">
          <span className="text-terminal text-glow">▲</span>
          <span className="text-text-dim">HIGH DENSITY</span>
        </span>
        <span className="flex items-center gap-1.5">
          <span className="text-amber text-glow-amber">⚠</span>
          <span className="text-text-dim">RESOURCE STRESS</span>
        </span>
        <span className="flex items-center gap-1.5">
          <span className="text-terminal/40">⣿</span>
          <span className="text-text-dim">LANDMASS</span>
        </span>
        <span className="flex items-center gap-1.5">
          <span className="text-text-dim/10">⠀</span>
          <span className="text-text-dim">OCEAN</span>
        </span>
      </div>
    </div>
  )
}
